export interface Listing {
  id: string
  address: string
  city: string
  state: string
  zip: string
  price?: number
  beds: number
  baths: number
  fullBaths?: number
  halfBaths?: number
  sqft: number
  lot: string
  description: string
  openHouse?: string
  features: string[]
  images: string[]
  video?: string
  hoa?: number
  yearBuilt?: number
  status: "active" | "sold" | "pending" | "inactive"
  mlsNumber?: string
  soldPrice?: number
  daysOnMarket?: number
}

// Active Listings
export const activeListings: Listing[] = [
  {
    id: "11-bluff-court",
    address: "11 Bluff Court SE",
    city: "Cartersville",
    state: "GA",
    zip: "30120",
    price: 595000,
    beds: 5,
    fullBaths: 3,
    halfBaths: 1,
    baths: 4,
    sqft: 3200,
    lot: "0.5 Acres",
    description:
      "Stunning 5-bedroom home in a desirable Cartersville neighborhood with exceptional space, modern finishes, and a layout perfect for families and entertaining.",
    features: [
      "5 Bedrooms",
      "3 Full Baths",
      "1 Half Bath",
      "Spacious Layout",
      "Modern Finishes",
      "Desirable Location",
    ],
    images: [],
    status: "active",
    mlsNumber: "10384776",
  },
  {
    id: "316-pin-oak",
    address: "316 Pin Oak Ave",
    city: "Woodstock",
    state: "GA",
    zip: "30188",
    price: 325000,
    beds: 2,
    baths: 3,
    fullBaths: 2,
    halfBaths: 1,
    sqft: 1438,
    lot: "2,613.6 sq.ft.",
    yearBuilt: 2005,
    hoa: 120,
    description:
      "Charming, light-filled home with vaulted ceilings, wainscoting, stone countertops, and a glass-enclosed patio. Upstairs loft provides flexible living space.",
    features: [
      "Vaulted Ceilings",
      "Stone Countertops",
      "Glass-Enclosed Patio",
      "Private Fenced Patio",
      "Clubhouse & Pool Access",
      "Tennis Courts",
    ],
    images: [
      "/images/316-20pin-20oak-20highres-1.jpg",
      "/images/316-20pin-20oak-20highres-2.jpg",
      "/images/316-20pin-20oak-20highres-6.jpg",
      "/images/316-20pin-20oak-20highres-8.jpg",
      "/images/316-20pin-20oak-20highres-17.jpg",
    ],
    status: "active",
  },
  {
    id: "608-wayside",
    address: "608 Wayside Road NE",
    city: "Rome",
    state: "GA",
    zip: "30161",
    price: 265000,
    beds: 3,
    baths: 2,
    fullBaths: 2,
    halfBaths: 0,
    sqft: 1472,
    lot: "1 Acre",
    description:
      "Beautifully maintained ranch-style home with metal roof, covered front porch, open floor plan, and a large yard framed by mature privacy trees. 10 minutes to Downtown Rome.",
    features: [
      "Metal Roof",
      "Covered Front Porch",
      "Open Floor Plan",
      "Board-and-Batten Detailing",
      "1 Acre Lot",
      "Mature Privacy Trees",
    ],
    images: [],
    status: "active",
  },
]

// Sold Listings (from Georgia MLS)
export const soldListings: Listing[] = [
  {
    id: "3784-overlook-trail",
    address: "3784 Overlook Trail NW",
    city: "Kennesaw",
    state: "GA",
    zip: "30144",
    soldPrice: 482000,
    beds: 5,
    baths: 4,
    fullBaths: 3,
    halfBaths: 1,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10489175",
    daysOnMarket: 47,
  },
  {
    id: "428-providence-walk",
    address: "428 Providence Walk Street",
    city: "Canton",
    state: "GA",
    zip: "30114",
    soldPrice: 625000,
    beds: 6,
    baths: 4,
    fullBaths: 4,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10459296",
    daysOnMarket: 58,
  },
  {
    id: "211-river-green",
    address: "211 River Green Avenue",
    city: "Canton",
    state: "GA",
    zip: "30114",
    soldPrice: 305000,
    beds: 3,
    baths: 3,
    fullBaths: 2,
    halfBaths: 1,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10436570",
    daysOnMarket: 36,
  },
  {
    id: "524-parkstone-lane",
    address: "524 Parkstone Lane",
    city: "Woodstock",
    state: "GA",
    zip: "30189",
    soldPrice: 340000,
    beds: 2,
    baths: 2,
    fullBaths: 1,
    halfBaths: 1,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10437159",
    daysOnMarket: 22,
  },
  {
    id: "1135-dunedin-trail",
    address: "1135 Dunedin Trail",
    city: "Woodstock",
    state: "GA",
    zip: "30188",
    soldPrice: 391000,
    beds: 3,
    baths: 3,
    fullBaths: 2,
    halfBaths: 1,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10367224",
    daysOnMarket: 36,
  },
  {
    id: "8-arrowhead-drive",
    address: "8 Arrowhead Drive",
    city: "Cartersville",
    state: "GA",
    zip: "30120",
    soldPrice: 350000,
    beds: 3,
    baths: 2,
    fullBaths: 2,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10342353",
    daysOnMarket: 23,
  },
  {
    id: "121-gum-wood-court",
    address: "121 Gum Wood Court",
    city: "Waleska",
    state: "GA",
    zip: "30183",
    soldPrice: 391900,
    beds: 3,
    baths: 2,
    fullBaths: 2,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10246646",
    daysOnMarket: 35,
  },
  {
    id: "36-benham-circle",
    address: "36 Benham Circle",
    city: "Cartersville",
    state: "GA",
    zip: "30120",
    soldPrice: 350000,
    beds: 5,
    baths: 3,
    fullBaths: 3,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10242307",
    daysOnMarket: 25,
  },
  {
    id: "243-neese-farm",
    address: "243 Neese Farm Drive",
    city: "Woodstock",
    state: "GA",
    zip: "30188",
    soldPrice: 578000,
    beds: 4,
    baths: 3,
    fullBaths: 2,
    halfBaths: 1,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10219369",
    daysOnMarket: 26,
  },
  {
    id: "211-kigian-trail",
    address: "211 Kigian Trail",
    city: "Woodstock",
    state: "GA",
    zip: "30188",
    soldPrice: 330000,
    beds: 3,
    baths: 3,
    fullBaths: 2,
    halfBaths: 1,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10235028",
    daysOnMarket: 25,
  },
  {
    id: "155-siniard-road",
    address: "155 Siniard Road NW",
    city: "Adairsville",
    state: "GA",
    zip: "30103",
    soldPrice: 585000,
    beds: 4,
    baths: 3,
    fullBaths: 3,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10175837",
    daysOnMarket: 61,
  },
  {
    id: "136-peach-blossom",
    address: "136 Peach Blossom Lane SE",
    city: "Calhoun",
    state: "GA",
    zip: "30701",
    soldPrice: 325000,
    beds: 5,
    baths: 3,
    fullBaths: 3,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10161357",
    daysOnMarket: 27,
  },
  {
    id: "137-alex-court",
    address: "137 Alex Court",
    city: "Calhoun",
    state: "GA",
    zip: "30701",
    soldPrice: 455000,
    beds: 5,
    baths: 3,
    fullBaths: 3,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10146962",
    daysOnMarket: 35,
  },
  {
    id: "1203-hickory-creek",
    address: "1203 Hickory Creek Court",
    city: "Woodstock",
    state: "GA",
    zip: "30188",
    soldPrice: 375000,
    beds: 3,
    baths: 2,
    fullBaths: 2,
    halfBaths: 0,
    sqft: 0,
    lot: "",
    description: "",
    features: [],
    images: [],
    status: "sold",
    mlsNumber: "10072435",
    daysOnMarket: 39,
  },
]

// Combined for backward compat
export const listings: Listing[] = [...activeListings, ...soldListings]
